# Generated by Django 4.2.1 on 2023-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='penalty_status',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
