# Generated by Django 4.2.1 on 2023-06-22 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_library', '0005_transaction_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent_per_day',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
