# Generated by Django 4.2.1 on 2023-06-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_library', '0006_book_rent_per_day_alter_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='borrowed_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='penalty_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='base_library.member'),
        ),
    ]
