# Generated by Django 4.2.1 on 2023-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_library', '0007_alter_member_borrowed_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='booka.jpeg', upload_to='book_covers/'),
        ),
    ]
