# Generated by Django 4.2.1 on 2023-06-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_library', '0008_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
